// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC415XMrfBtlUTGZvthHLqjH8BNoeCt83Y',
    appId: '1:89562759161:web:163ac4ec2609fd997a8728',
    messagingSenderId: '89562759161',
    projectId: 'task-manager-2533a',
    authDomain: 'task-manager-2533a.firebaseapp.com',
    storageBucket: 'task-manager-2533a.appspot.com',
    measurementId: 'G-3ME1WHG3XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQyYdJ9500MbGHVFhCE-uMMl8YgF0kNYY',
    appId: '1:89562759161:android:64dd5605bb88cf7a7a8728',
    messagingSenderId: '89562759161',
    projectId: 'task-manager-2533a',
    storageBucket: 'task-manager-2533a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1zrSyG_JAtjDKTGrbJmjoUPRcejWsF5o',
    appId: '1:89562759161:ios:30cbe2ed7b6c591f7a8728',
    messagingSenderId: '89562759161',
    projectId: 'task-manager-2533a',
    storageBucket: 'task-manager-2533a.appspot.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1zrSyG_JAtjDKTGrbJmjoUPRcejWsF5o',
    appId: '1:89562759161:ios:30cbe2ed7b6c591f7a8728',
    messagingSenderId: '89562759161',
    projectId: 'task-manager-2533a',
    storageBucket: 'task-manager-2533a.appspot.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC415XMrfBtlUTGZvthHLqjH8BNoeCt83Y',
    appId: '1:89562759161:web:23c9d549b194a62e7a8728',
    messagingSenderId: '89562759161',
    projectId: 'task-manager-2533a',
    authDomain: 'task-manager-2533a.firebaseapp.com',
    storageBucket: 'task-manager-2533a.appspot.com',
    measurementId: 'G-FNRQQ96635',
  );

}